### ISSUE TITLE
Show commits

### ISSUE THREAD

**Issue by johnletey** [JasonEtco/activity-box#1]
As of right now, this app only outputs activity on issues and pull requests ... it would be nice to have commits as well (not just in the users repository but also any commits that the user creates)

**Comment by johnletey** [comment]
Of course ... only public contributions 😄

**Comment by JasonEtco** [comment]
Just realized you opened these issues but I wasn't watching my own repos 😱 

So this is how it worked originally, but it became way too dominated by commits. It might just be for me, I tend to make many small commits, but it meant that I wasn't seeing more general information about my activity.

**Comment by johnletey** [comment]
> but I wasn't watching my own repos 😱

Yikes 😱

> but it became way too dominated by commits ... but it meant that I wasn't seeing more general information about my activity.

Now that I think about it ... I completely agree. Let's leave the tool as is for now.
