### ISSUE TITLE
@octokit/request was removed (?)

### ISSUE THREAD

**Issue by pujux** [JasonEtco/activity-box#19]
Check Action error, somehow the package was removed from the npm registry, any ideas on how to fix this?

**Comment by Zalbani** [comment]
The problem seems to have been temporary. The @octokit/request dependency is still available: [https://www.npmjs.com/package/@octokit/request](https://www.npmjs.com/package/@octokit/request)

**Comment by pujux** [comment]
Oh yeah I see! Nice!
