### ISSUE TITLE
Refactor GitHub Actions config

### ISSUE THREAD

**Issue by johnletey** [JasonEtco/activity-box#2]
With the release of scheduled GitHub Action runs, we can also do the same thing as CircleCI.

Resource: https://developer.github.com/actions/changes/2019-04-05-scheduling-workflows/

**Comment by johnletey** [comment]
@JasonEtco Do you still want to keep this open? https://github.com/JasonEtco/activity-box/pull/3#issuecomment-480525792

**Comment by JasonEtco** [comment]
I've got a PR on the way that'll close this 👌
