### ISSUE TITLE
Too many no changes gist revisions

### ISSUE THREAD

**Issue by Smankusors** [JasonEtco/activity-box#20]
Currently the current cron job will always update the gist regardless if there's any changes. For example, you can look at [my gist revisions](https://gist.github.com/Smankusors/3c2c46cff925fd415cb1e477a3c1234b/revisions) (currently inactive)

It's hard to track the activites with a lot of no changes here, perhaps just commit when there's any changes?

Thanks,
Smankusors

**Comment by JasonEtco** [comment]
Thanks for the issue @Smankusors. We can add a check to only update the Gist if there aren't any changes, just using string equality checks.

Out of curiosity, what is this preventing you from doing? Is there a problem with seeing all the empty changes?

**Comment by Smankusors** [comment]
hmm last time it's completely broken, it cannot build the docker image. I got this error below

```
  npm ERR! code E404
  npm ERR! 404 Not Found - GET https://registry.npmjs.org/@jest/core/-/core-26.0.1.tgz
  npm ERR! 404 
  npm ERR! 404  '@jest/core@26.0.1' is not in the npm registry.
  npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
  npm ERR! 404 
  npm ERR! 404 Note that you can also install from a
  npm ERR! 404 tarball, folder, http url, or git url.
```

The package is not just `@jest/core@26.0.1`, there's also `@octokit/request@5.4.3`, `@sinonjs/fake-timers@6.0.1`, `@octokit/rest@17.9.2`.

And this error being repeated thrown, spamming my GitHub notification, so for temporary I shut it down. I'm not sure what's happened... Is the package-lock.json out of date? Maybe because I didn't merge request "bump lodash"? Maybe just temporary downtime from npm registry?

**Comment by JasonEtco** [comment]
I'm not sure what's going wrong - I haven't had any problems, the code is running in this repository (not sure if you can [see the Actions tab](https://github.com/JasonEtco/activity-box/actions)) and has been forever 🤷‍♂️ 

> hmm last time it's completely broken, it cannot build the docker image. I got this error below

This is unrelated to the amount of Gist commits though.

**Comment by Smankusors** [comment]
> I'm not sure what's going wrong - I haven't had any problems, the code is running in this repository (not sure if you can [see the Actions tab](https://github.com/JasonEtco/activity-box/actions)) and has been forever 🤷‍♂️

Oh yeah I can see yours... Then you can see [mine](https://github.com/Smankusors/activity-box/actions). Well to be honest I see similiar timestamp of failing build (11 days ago). So I think it's safe to say it's just npm downtime...

> This is unrelated to the amount of Gist commits though.

Well, I don't say it's related, your curiosity asked it 😉

**Comment by JasonEtco** [comment]
Okay, in that case I'm going to close this, it does line up with [npm's status history](https://status.npmjs.org/). If needing to prevent noop commits is important to you, feel free to open a PR - you'd have to add an additional API call here to get the existing contents:

https://github.com/JasonEtco/activity-box/blob/24bbb8ddcc6f8a79addf11d11c7254221843f19a/index.js#L59

You can do that via `box.get()`:

```js
const { data } = await box.get()
if (data.files[0].content === content) return
```
