### ISSUE TITLE
Deleting gist file

### ISSUE THREAD

**Issue by ksteflovic** [JasonEtco/activity-box#23]
Instead of addind the activity to gist file, it keeps deleting my gist file 😄 

Can you help me?

**Comment by JasonEtco** [comment]
I'm not quite sure how that's possible 😅 it doesn't make an API calls to delete the file. 

https://github.com/JasonEtco/activity-box/blob/24bbb8ddcc6f8a79addf11d11c7254221843f19a/index.js#L56-L65

Is there any more context or information you can provide?

**Comment by ksteflovic** [comment]
Thank you for your help. It is working now by a magic.
