### ISSUE TITLE
Trigger workflow isn't working

### ISSUE THREAD

**Issue by VianaSamuel** [JasonEtco/activity-box#39]
Edit: The workflow is running properly, but only automatically (through cron).
I was trying to trigger it manually, and that's why it wasn't working.

**Comment by VianaSamuel** [comment]
PS: The PAT is staten as "never used".
![image](https://user-images.githubusercontent.com/101417449/171986714-17dbe689-0021-426f-b113-d0f7085fdf4a.png)
PS²:  Apparently, the activity-box.yml file isn't being executed in the actions.
![image](https://user-images.githubusercontent.com/101417449/171986774-803ff332-3a8b-4abe-97ad-d3095c4732fd.png)
![image](https://user-images.githubusercontent.com/101417449/171986786-e7b43586-dac4-4372-bd15-fa12f27fb49a.png)

**Comment by djLee77** [comment]
Hello, I'm experiencing the same problem right now, so can you tell me how you solved it? 
I even added the phrase 'We couldn't find any files to show' to the gist after it runs automatically. 🫠
